server.port=8080

spring.datasource.url = jdbc:mysql://monorail.proxy.rlwy.net:30486/railway
spring.datasource.username = root
spring.datasource.password = Ionut2004
spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
spring.jpa.defer-datasource-initalization = true
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
